# Generated by Django 3.2.6 on 2021-08-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210816_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.typesubscribe'),
        ),
    ]
