# Generated by Django 3.2.6 on 2021-08-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210817_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typesubscribe',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
