# Generated by Django 3.2.6 on 2021-08-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
