# Generated by Django 3.2.6 on 2021-09-05 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days_Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default='1', max_length=15)),
                ('time', models.CharField(choices=[('8:30', '8:30'), ('10:00', '10:00'), ('11:30', '11:30'), ('13:00', '13:00'), ('14:30', '14:30'), ('16:00', '16:00'), ('17:30', '17:30')], default='1', max_length=6)),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student_group')),
            ],
        ),
    ]
